---
 
- hosts: all
  become: true
  pre_tasks:

   - name: install updates (CentOS)
     tags: always
     dnf:
       name: "*"
       state: latest
       update_cache: yes
     when: ansible_distribution == "CentOS"
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

    - name: add ssh key for ghost
      tags: always
      authorized_key:
        user: ghost
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICwR3OsA2RpNyyDAQSXBNy4CbuphBtJFcoG1HGFqGAoa ansible"
    
- hosts: workstations
  become: true
  tasks:
  
  - name: install unzip
    package:
      name: unzip
  
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
     name:
       - apache2
       - libapache2-mod-php
     state: latest
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS servers
    tags: apache,httpd,centos
    dnf:
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change email in apache config file
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "^ServerAdmin"
      line: ServerAdmin somebody@somewhere.something
    when: ansible_distribution == "CentOS"
    register : httpd_mail
  
  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: restarted
    when: httpd_mail.changed


  - name: copy default html for site
    tags: apache,httpd,centos
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb (CentOS)
    tags: db,mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: Install mariadb (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba (CentOS and Ubuntu)
    tags: samba
    package:
      name: samba
      state: latest
